# Bench Server 配置文件

# 服务器配置
server:
  port: "8080"

# 数据库配置
database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  name: "bench_server"
  max_open_conns: 25
  max_idle_conns: 5

# 日志配置
logging:
  level: "info"
  format: "json"

# 应用配置
app:
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s" 